# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import user_search_pb2 as protos_dot_user__search__pb2


class UserSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/UserSearch/ListUsers',
                request_serializer=protos_dot_user__search__pb2.SearchRequest.SerializeToString,
                response_deserializer=protos_dot_user__search__pb2.SearchResponse.FromString,
                )
        self.ListUsersStreamRequestSingleResponse = channel.stream_unary(
                '/UserSearch/ListUsersStreamRequestSingleResponse',
                request_serializer=protos_dot_user__search__pb2.SearchRequest.SerializeToString,
                response_deserializer=protos_dot_user__search__pb2.SearchResponse.FromString,
                )
        self.ListUsersSingleRequestStreamResponse = channel.unary_stream(
                '/UserSearch/ListUsersSingleRequestStreamResponse',
                request_serializer=protos_dot_user__search__pb2.SearchRequest.SerializeToString,
                response_deserializer=protos_dot_user__search__pb2.SearchResponse.FromString,
                )
        self.ListUsersStreamRequestStreamResponse = channel.stream_stream(
                '/UserSearch/ListUsersStreamRequestStreamResponse',
                request_serializer=protos_dot_user__search__pb2.SearchRequest.SerializeToString,
                response_deserializer=protos_dot_user__search__pb2.SearchResponse.FromString,
                )


class UserSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsersStreamRequestSingleResponse(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsersSingleRequestStreamResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsersStreamRequestStreamResponse(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=protos_dot_user__search__pb2.SearchRequest.FromString,
                    response_serializer=protos_dot_user__search__pb2.SearchResponse.SerializeToString,
            ),
            'ListUsersStreamRequestSingleResponse': grpc.stream_unary_rpc_method_handler(
                    servicer.ListUsersStreamRequestSingleResponse,
                    request_deserializer=protos_dot_user__search__pb2.SearchRequest.FromString,
                    response_serializer=protos_dot_user__search__pb2.SearchResponse.SerializeToString,
            ),
            'ListUsersSingleRequestStreamResponse': grpc.unary_stream_rpc_method_handler(
                    servicer.ListUsersSingleRequestStreamResponse,
                    request_deserializer=protos_dot_user__search__pb2.SearchRequest.FromString,
                    response_serializer=protos_dot_user__search__pb2.SearchResponse.SerializeToString,
            ),
            'ListUsersStreamRequestStreamResponse': grpc.stream_stream_rpc_method_handler(
                    servicer.ListUsersStreamRequestStreamResponse,
                    request_deserializer=protos_dot_user__search__pb2.SearchRequest.FromString,
                    response_serializer=protos_dot_user__search__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserSearch/ListUsers',
            protos_dot_user__search__pb2.SearchRequest.SerializeToString,
            protos_dot_user__search__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsersStreamRequestSingleResponse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/UserSearch/ListUsersStreamRequestSingleResponse',
            protos_dot_user__search__pb2.SearchRequest.SerializeToString,
            protos_dot_user__search__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsersSingleRequestStreamResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/UserSearch/ListUsersSingleRequestStreamResponse',
            protos_dot_user__search__pb2.SearchRequest.SerializeToString,
            protos_dot_user__search__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListUsersStreamRequestStreamResponse(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/UserSearch/ListUsersStreamRequestStreamResponse',
            protos_dot_user__search__pb2.SearchRequest.SerializeToString,
            protos_dot_user__search__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
